#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

#cat /etc/s6-overlay/s6-rc.d/init-adduser/branding

echo '
----------------------------------------------------------
   _  __________  ____  ______  _____ ____  _____  ___  __
  | |/ /_  __/ / / / / / / __ \/ ___// __ \/   \ \/ / |/ /
  |   / / / / /_/ / / / / /_/ /\__ \/ / / / /| |\  /|   / 
 /   | / / / __  / /_/ / _, _/___/ / /_/ / ___ |/ //   |  
/_/|_|/_/ /_/ /_/\____/_/ |_|/____/_____/_/  |_/_//_/|_|  

Brought to you by xthursdayx
----------------------------------------------------------
GID/UID
----------------------------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

lsiown abc:abc /app
lsiown abc:abc /config
lsiown abc:abc /defaults
