#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/.config/gPodder

# set webserver port on first install
[[ ! -f /config/.config/gPodder/server-config.txt ]] && \
  echo "port 3000" > /config/.config/gPodder/server-config.txt

if [ -n "$PASSWORD" ]; then
    echo "abc:${PASSWORD}" | chpasswd
    echo "**** Setting password from environment variable. ****"
else
    echo "**** No auth enabled. To enable auth, you can set the PASSWORD var in docker arguments. ****"
fi

# permissions
chown -R abc:abc \
	/config \
	/gpodder \
	/downloads 
