name: Benchmark and Lint Dockerfiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Benchmark_dark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Sysdig CIS Dockerfile Benchmark
        uses: sysdiglabs/benchmark-dockerfile@v1.0.0
        with:
         directory: /dark
         trustedBaseImages: lsiobase/rdesktop-web 

  Benchmark_light:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Sysdig CIS Dockerfile Benchmark
        uses: sysdiglabs/benchmark-dockerfile@v1.0.0
        with:
         directory: /light
         trustedBaseImages: lsiobase/rdesktop-web 

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: |
            light/Dockerfile
            dark/Dockerfile
