#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/.config/gPodder

# set webserver port on first install
[[ ! -f /config/.config/gPodder/server-config.txt ]] && \
  echo "port 3000" > /config/.config/gPodder/server-config.txt

sed -i 's|"password":"abc",|"password":"kjhbouygiuvhgvghv",|' /gclient/app.js
sed -i "s#process.env.PASSWORD || 'abc';#process.env.PASSWORD || 'kjhbouygiuvhgvghv';#" /gclient/maketoken.js

if [ -n "$PASSWORD" ]; then
    echo "abc:${PASSWORD}" | chpasswd
    echo "Setting password from environment variable."
else 
    echo "abc:kjhbouygiuvhgvghv" | chpasswd
    echo "No password is set for the interface."
fi

# permissions
chown -R abc:abc \
	/config \
	/gpodder \
	/downloads 
