#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/.config/gPodder

# set webserver port on first install
if [ ! -f /config/.config/gPodder/server-config.txt ]; then
  echo "port 8080" > /config/.config/gPodder/server-config.txt
fi

# permissions
chown -R abc:abc \
	/config \
	/gpodder \
	/downloads 
